//yes when page loads
$('.h2').click(function() {
    $('.p1').slideDown();
    $('.p1half').show();
    $('.p1seventh').show();
    $('.p1eight').show();
    $('.p1nineth').show();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.p21').hide();
    $('.p22').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p23').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').slideUp();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#ccff99");
});

$(".h2").hover(function() {
    $(".h2").css("background-color", "#ffffb3");
}, function() {
    $(".h2").css("background-color", "");
});


//yes help find glasses
$('.p1eight').click(function() {
    $('.p19').show();
    $('.house').slideDown();
    $('.p20').show();
    $('.p1').hide();
    $('.p1eight').slideUp();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1nineth').hide();
    $('.p21').hide();
    $('.p22').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p23').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", " #ff6699");
});

$(".p1eight").hover(function() {
    $(".p1eight").css("background-color", "#ff66ff");
}, function() {
    $(".p1eight").css("background-color", "");
});

//choose to not help find glasses
$('.p1nineth').click(function() {
    $('.p2').slideDown();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.p21').hide();
    $('.p22').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p23').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.h1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#ff5c33");
});

$(".p1nineth").hover(function() {
    $(".p1nineth").css("background-color", "#ff66ff");
}, function() {
    $(".p1nineth").css("background-color", "");
});


//when the house is double cliked
$('.house').dblclick(function() {
    $('.p21').slideDown();
    $('.p22').slideDown();
    $('.optiondresser').slideDown();
    $('.optionsofa').slideDown();
    $('.optionbed').slideDown();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').slideUp();
    $('.p21').hide();
    $('.p22').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p23').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').slideUp();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "  #33ff99");
});

//when I hover over all three options
$(".optiondresser").hover(function() {
    $(".optiondresser").css("background-color", "#ffffb3");
}, function() {
    $(".optiondresser").css("background-color", "");
});

$(".optionsofa").hover(function() {
    $(".optionsofa").css("background-color", "#ffffb3");
}, function() {
    $(".optionsofa").css("background-color", "");
});

$(".optionbed").hover(function() {
    $(".optionbed").css("background-color", "#ffffb3");
}, function() {
    $(".optionbed").css("background-color", "");
});


//when the option dresser is cliked
$('.optiondresser').click(function() {
    $('.p23').slideDown();
    $('.imgdresser').slideDown();
    $('.optiondresser').slideUp();
    $('.optionsofa').slideUp();
    $('.optionbed').slideUp();
    $('.p22').slideUp();
    $('.p21').slideUp();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').slideUp();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').slideUp();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#f5f5f0");
});

//when the dresser is opened
$('.imgdresser').click(function() {
    $('.p24').show();
    $('.emptydresser').show();
    $('.p23').slideUp();
    $('.imgdresser').slideUp();
    $('.container').slideDown();
    $('.p22').hide();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').slideUp();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#f5f5f0");
});

//when the image is cliked, goes back to the three options
$('.emptydresser').dblclick(function() {
    $('.optionsofa').slideDown();
    $('.optionbed').slideDown();
    $('.optiondresser').slideDown();
    $('.emptydresser').slideUp();
    $('.p24').hide();
    $('.p23').hide();
    $('.imgdresser').hide();
    $('.p22').slideDown();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "  #33ff99");
});

//when the option sofa is cliked
$('.optionsofa').click(function() {
    $('.ptwo5').slideDown();
    $('.imgsofa').slideDown();
    $('.imgdresser').hide();
    $('.optiondresser').slideUp();
    $('.optionsofa').slideUp();
    $('.optionbed').slideUp();
    $('.p22').slideUp();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').slideUp();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').slideUp();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "  #e7bf97");
});

//click to clear out the sofa
$('.imgsofa').click(function() {
    $('.p24').slideDown();
    $('.sofawithoutpillows').slideDown();
    $('.ptwo5').slideUp();
    $('.imgsofa').slideUp();
    $('.imgdresser').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p22').hide();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.imgdresser').hide();
    $('.emptydresser').hide();
    $('.sofawithoutpillows').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').slideUp();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "  #e7bf97");
});


//when this image is cliked goes back to three options
$('.sofawithoutpillows').dblclick(function() {
    $('.p22').slideDown();
    $('.imgsofa').hide();
    $('.imgdresser').hide();
    $('.optiondresser').slideDown();
    $('.optionsofa').slideDown();
    $('.optionbed').slideDown();
    $('.sofawithoutpillows').slideUp();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').slideUp();
    $('.imgdresser').hide();
    $('.p24').slideUp();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.p26').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').slideUp();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "  #33ff99");
});

//when bed option is clicked change to bed
$('.optionbed').click(function() {
    $('.p26').slideDown();
    $('.bed').slideDown();
    $('.optiondresser').slideUp();
    $('.optionsofa').slideUp();
    $('.optionbed').slideUp();
    $('.p22').slideUp();
    $('.p21').slideUp();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#e6ffff");
});

//double click on the bed to take a closer look  at the nightstand
$('.bed').dblclick(function() {
    $('.p27').show();
    $('.nightstand').show();
    $('.p28').show();
    $('.p26').slideUp();
    $('.bed').slideUp();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p22').hide();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p32').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#e6ffff");
});


//put the old woman her glasses
$('.nightstand').dblclick(function() {
    $('.p29').show();
    $('.womenglasses').slideDown();
    $('.p30').show();
    $('.p31').show();
    $('.p32').show();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p26').hide();
    $('.bed').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p22').hide();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.p33').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#ff99cc");
});

//no 2
$('.p32').click(function() {
    $('.p33').show();
    $('.p29').slideUp();
    $('.womenglasses').slideUp();
    $('.p30').slideUp();
    $('.p31').slideUp();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p26').hide();
    $('.bed').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p22').hide();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
});
//choose yes or no to continue on 
$(".p31").hover(function() {
    $(".p31").css("background-color", "#ffffb3");
}, function() {
    $(".p31").css("background-color", "");
});

$(".p32").hover(function() {
    $(".p32").css("background-color", "#ffffb3");
}, function() {
    $(".p32").css("background-color", "");
});


//continue the mystery
$('.p31').click(function() {
    $('.h4').show();
    $('.p3').show();
    $('.mag').show();
    $('.p32').hide();
    $('.p31').hide();
    $('.p33').hide();
    $('.p29').hide();
    $('.womenglasses').hide();
    $('.p30').hide();
    $('.p31').hide();
    $('.p27').hide();
    $('.nightstand').hide();
    $('.p28').hide();
    $('.p26').hide();
    $('.bed').hide();
    $('.optiondresser').hide();
    $('.optionsofa').hide();
    $('.optionbed').hide();
    $('.p22').hide();
    $('.p21').hide();
    $('.p1').hide();
    $('.p1half').hide();
    $('.p1seventh').hide();
    $('.p1eight').hide();
    $('.p1nineth').hide();
    $('.p19').hide();
    $('.p20').hide();
    $('.house').hide();
    $('.imgdresser').hide();
    $('.p24').hide();
    $('.emptydresser').hide();
    $('.p25').hide();
    $('.imgsofa').hide();
    $('.sofawithoutpillows').hide();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $('.p2four').hide();
    $("body").css("background-color", "#66ffff");
});


//No
$('.h3').click(function() {
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').show();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $("body").css("background-color", "#f0e6ff");
    $('.p18').hide();
});

$(".h3").hover(function() {
    $(".h3").css("background-color", "#ffffb3");
}, function() {
    $(".h3").css("background-color", "");
});





//maginfying glass
$('.mag').dblclick(function() {
    $('.man1').show();
    $('.man2').show();
    $('.h5').show();
    $('.p4').show();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').slideUp();
    $('.p3').slideUp();
    $('.mag').slideUp();
    $('.testimony1').show();
    $('.p5').hide();
    $('.testimony2').show();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.p18').hide();
    $('.garbagecan').hide();
    $("body").css("background-color", "#ff6666");

});

//Testimony#1
$('.testimony1').click(function() {
    $('.p5').toggle();
    $('.p6').hide();
    $('.man2').toggle();
    $('.man1').show();
    $('.h5').show();
    $('.p4').show();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.testimony2').toggle();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $(".testimony1").css("background-color", "#8c8c8c");
});


//testimony2
$('.testimony2').click(function() {
    $('.p6').toggle();
    $('.p5').hide();
    $('.man1').toggle();
    $('.man2').show();
    $('.h5').show();
    $('.p4').show();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.testimony1').toggle();
    $('.Next-button').show();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.p18').hide();
    $(".testimony2").css("background-color", "#8c8c8c");

});


//Next button is clicked to lead to the next page 
$(".Next-button").click(function() {
    $('.h6').show();
    $('.p7').show();
    $('.p8').show();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').show();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').show();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.Next-button').hide();
    $('.p18').hide();
    $("body").css("background-color", " #ff99bb");
});

$(".Next-button").hover(function() {
    $(".Next-button").css("background-color", "#ffffb3");
}, function() {
    $(".Next-button").css("background-color", "");

});
$(".Next-button").hover(function() {
    $(".Next-button").css("border-color", "#00ff00");
}, function() {
    $(".Next-button").css("border-color", "");
});


//phaseman1: when the user clicks to say that Man 1 is guilty
$(".p7").click(function() {
    $('.p9').slideDown();
    $('.p10').slideDown();
    $('.man1').show();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p8').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.garbagecan').hide();
    $('.h6').slideUp();
    $('.p7').slideUp();
    $('.p8').slideUp();
    $('.p18').hide();
    $("body").css("background-color", "#ffe6f0");
});

$(".p7").hover(function() {
    $(".p7").css("color", "#80ff80");
}, function() {
    $(".p7").css("color", "");
});



//give back the old women her purse & change to Moneyhand all together
$(".p10").click(function() {
    $('.purse').show(4000);
    $('.p11').show(200);
    $('.p12').toggle(200);
    $('.p13').toggle();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.moneyhand').toggle(10000);
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.p18').hide();
    $('.garbagecan').hide();
    $(".purse").slideUp(300);
    $("body").css("background-color", "#ff9f80");
});

$(".here").hover(function() {
    $(".here").css("color", "yellow");
}, function() {
    $(".here").css("color", "");
    $(".here").text("Here⬅");
}, function() {
    $(".here").text("");
});


//Double click to see the money fall from the sky
$(".moneyhand").dblclick(function() {
    $('.moneyfallfromsky').show();
    $('.p14').slideDown();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').slideUp();
    $('.p13').hide();
    $('.p15').hide();
    $('.p16').hide();
    $('.p17').hide();
    $('.p18').hide();
    $('.garbagecan').hide();
});


$(".p8").hover(function() {
    $(".p8").css("color", "#99ffff");
}, function() {
    $(".p8").css("color", "");
});


//The result of saying that man 2 is guilty
$(".p8").click(function() {
    $('.p15').slideDown();
    $('.p16').slideDown();
    $('.garbagecan').slideDown();
    $('.p17').slideDown();
    $('.p18').slideDown();
    $('.women').hide();
    $('.h3').hide();
    $('.h2').hide();
    $('.p2').hide();
    $('.h1').hide();
    $('.p1').hide();
    $('.h4').hide();
    $('.p3').hide();
    $('.mag').hide();
    $('.h5').hide();
    $('.p4').hide();
    $('.man1').hide();
    $('.testimony1').hide();
    $('.p5').hide();
    $('.man2').hide();
    $('.testimony2').hide();
    $('.p6').hide();
    $('.Next-button').hide();
    $('.h6').hide();
    $('.p7').hide();
    $('.p8').hide();
    $('.p9').hide();
    $('.p10').hide();
    $('.purse').hide();
    $('.p11').hide();
    $('.p12').hide();
    $('.moneyhand').hide();
    $('.p13').hide();
    $('.monefallfromsky').hide();
    $('.p14').hide();
    $("body").css("background-color", "#ff3333");
});